server:
  port: 8888  # Config server runs on port 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dzsodie/melita-config-repo
          default-label: main
