server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dzsodie/melita-config-repo
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
